import type { GuestSection } from "@/lib/types";

export const MOCK_LEDGER_DATA: GuestSection[] = [
  {
    sectionName: "Shekha Mujal",
    entries: [
      {
        id: "sm-1",
        originalText: "Abbas Mithaiwala",
        cleanedNames: "Abbasbhai Mithaiwala",
        gender: "gents",
        ladiesCount: 0,
        gentsCount: 1,
        kidsCount: 0,
        totalCount: 1,
      },
      {
        id: "sm-2",
        originalText: "Batul chattriwala",
        cleanedNames: "Batulben Chattriwala",
        gender: "ladies",
        ladiesCount: 1,
        gentsCount: 0,
        kidsCount: 0,
        totalCount: 1,
      },
      {
        id: "sm-3",
        originalText: "Sakina & Nafeesa Attarwala",
        cleanedNames: "Sakinaben & Nafeesaben Attarwala",
        gender: "ladies",
        ladiesCount: 2,
        gentsCount: 0,
        kidsCount: 0,
        totalCount: 2,
      },
    ],
  },
  {
    sectionName: "Bhaiwada ni Pole",
    entries: [
      {
        id: "bp-1",
        originalText: "Sabhiya",
        cleanedNames: "Sabhiyaben",
        gender: "ladies",
        ladiesCount: 1,
        gentsCount: 0,
        kidsCount: 0,
        totalCount: 1,
      },
      {
        id: "bp-2",
        originalText: "Munira tinwala",
        cleanedNames: "Muniraben Tinwala",
        gender: "ladies",
        ladiesCount: 1,
        gentsCount: 0,
        kidsCount: 0,
        totalCount: 1,
      },
    ],
  },
  {
    sectionName: "Makeriwad",
    entries: [
      {
        id: "mw-1",
        originalText: "Arwaben tinwala",
        cleanedNames: "Arwaben Tinwala",
        gender: "ladies",
        ladiesCount: 1,
        gentsCount: 0,
        kidsCount: 0,
        totalCount: 1,
      },
      {
        id: "mw-2",
        originalText: "Fatema Barodawala",
        cleanedNames: "Fatemaben Barodawala",
        gender: "ladies",
        ladiesCount: 1,
        gentsCount: 0,
        kidsCount: 1,
        totalCount: 2,
      },
    ],
  },
  {
    sectionName: "Zakariya",
    entries: [
      {
        id: "zk-1",
        originalText: "Azizbhai lokhandwala",
        cleanedNames: "Azizbhai Lokhandwala",
        gender: "gents",
        ladiesCount: 2,
        gentsCount: 3,
        kidsCount: 1,
        totalCount: 6,
      },
      {
        id: "zk-10",
        originalText: "Abulibhai & Nafeesa Mansa",
        cleanedNames: "Abulibhai & Nafeesaben Mansa",
        gender: "mixed",
        ladiesCount: 1,
        gentsCount: 1,
        kidsCount: 0,
        totalCount: 2,
      },
    ],
  },
];

export const MOCK_RSVP_DATA = [
  {
    id: "1",
    name: "Abbasbhai Mithaiwala",
    status: "Accepted" as const,
    ladies: 0,
    gents: 1,
    kids: 0,
    timestamp: "2 mins ago",
  },
  {
    id: "2",
    name: "Batulben Chattriwala",
    status: "Accepted" as const,
    ladies: 1,
    gents: 0,
    kids: 0,
    timestamp: "1 hour ago",
  },
];
